// Export utilities for CSV and PDF generation

/**
 * Convert array of objects to CSV string
 */
export function convertToCSV(data: any[], headers?: string[]): string {
  if (!data || data.length === 0) return '';

  // Get headers from first object if not provided
  const csvHeaders = headers || Object.keys(data[0]);

  // Create CSV header row
  const headerRow = csvHeaders.join(',');

  // Create CSV data rows
  const dataRows = data.map((row) => {
    return csvHeaders
      .map((header) => {
        const value = row[header];
        // Handle values that contain commas or quotes
        if (typeof value === 'string' && (value.includes(',') || value.includes('"'))) {
          return `"${value.replace(/"/g, '""')}"`;
        }
        return value ?? '';
      })
      .join(',');
  });

  return [headerRow, ...dataRows].join('\n');
}

/**
 * Download CSV file
 */
export function downloadCSV(data: any[], filename: string, headers?: string[]): void {
  const csv = convertToCSV(data, headers);
  const blob = new Blob([csv], { type: 'text/csv;charset=utf-8;' });
  const link = document.createElement('a');
  
  if (link.download !== undefined) {
    const url = URL.createObjectURL(blob);
    link.setAttribute('href', url);
    link.setAttribute('download', `${filename}.csv`);
    link.style.visibility = 'hidden';
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  }
}

/**
 * Generate simple PDF using HTML canvas (basic implementation)
 */
export function downloadPDF(
  content: string,
  filename: string,
  options?: {
    title?: string;
    orientation?: 'portrait' | 'landscape';
  }
): void {
  // Create a printable window
  const printWindow = window.open('', '_blank');
  if (!printWindow) {
    alert('Please allow popups to download PDF');
    return;
  }

  const title = options?.title || filename;
  const orientation = options?.orientation || 'portrait';

  printWindow.document.write(`
    <!DOCTYPE html>
    <html>
      <head>
        <title>${title}</title>
        <style>
          @page {
            size: ${orientation};
            margin: 20mm;
          }
          body {
            font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif;
            line-height: 1.6;
            color: #333;
            max-width: 100%;
            margin: 0;
            padding: 20px;
          }
          h1 {
            color: #395192;
            border-bottom: 2px solid #06B6D4;
            padding-bottom: 10px;
            margin-bottom: 20px;
          }
          h2 {
            color: #395192;
            margin-top: 24px;
            margin-bottom: 12px;
          }
          table {
            width: 100%;
            border-collapse: collapse;
            margin: 20px 0;
          }
          th, td {
            border: 1px solid #ddd;
            padding: 12px;
            text-align: left;
          }
          th {
            background-color: #395192;
            color: white;
            font-weight: 600;
          }
          tr:nth-child(even) {
            background-color: #f9f9f9;
          }
          .footer {
            margin-top: 40px;
            padding-top: 20px;
            border-top: 1px solid #ddd;
            font-size: 12px;
            color: #666;
            text-align: center;
          }
        </style>
      </head>
      <body>
        ${content}
        <div class="footer">
          Generated by CerebroLearn on ${new Date().toLocaleString()}
        </div>
      </body>
    </html>
  `);

  printWindow.document.close();
  
  // Wait for content to load, then print
  printWindow.onload = () => {
    printWindow.print();
    // Close the window after printing
    setTimeout(() => {
      printWindow.close();
    }, 500);
  };
}

/**
 * Export table data to CSV
 */
export function exportTableToCSV(tableId: string, filename: string): void {
  const table = document.getElementById(tableId) as HTMLTableElement;
  if (!table) {
    console.error(`Table with id "${tableId}" not found`);
    return;
  }

  const rows: string[][] = [];
  const tableRows = table.querySelectorAll('tr');

  tableRows.forEach((row) => {
    const cols: string[] = [];
    const cells = row.querySelectorAll('th, td');
    
    cells.forEach((cell) => {
      let text = cell.textContent || '';
      // Clean up the text
      text = text.trim().replace(/\s+/g, ' ');
      // Handle commas and quotes
      if (text.includes(',') || text.includes('"')) {
        text = `"${text.replace(/"/g, '""')}"`;
      }
      cols.push(text);
    });
    
    if (cols.length > 0) {
      rows.push(cols);
    }
  });

  const csv = rows.map(row => row.join(',')).join('\n');
  const blob = new Blob([csv], { type: 'text/csv;charset=utf-8;' });
  const link = document.createElement('a');
  
  const url = URL.createObjectURL(blob);
  link.setAttribute('href', url);
  link.setAttribute('download', `${filename}.csv`);
  link.style.visibility = 'hidden';
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}

/**
 * Generate PDF from table
 */
export function exportTableToPDF(tableId: string, filename: string, title?: string): void {
  const table = document.getElementById(tableId) as HTMLTableElement;
  if (!table) {
    console.error(`Table with id "${tableId}" not found`);
    return;
  }

  const tableHTML = table.outerHTML;
  const content = `
    <h1>${title || filename}</h1>
    ${tableHTML}
  `;

  downloadPDF(content, filename, { title: title || filename });
}

/**
 * Generate HTML content for PDF from data
 */
export function generateHTMLReport(data: {
  title: string;
  sections: Array<{
    heading: string;
    content: string;
  }>;
  stats?: Array<{
    label: string;
    value: string | number;
  }>;
}): string {
  let html = `<h1>${data.title}</h1>`;

  // Add stats if provided
  if (data.stats && data.stats.length > 0) {
    html += '<div style="display: grid; grid-template-columns: repeat(auto-fit, minmax(200px, 1fr)); gap: 20px; margin: 20px 0;">';
    data.stats.forEach(stat => {
      html += `
        <div style="border: 1px solid #ddd; padding: 16px; border-radius: 8px; background: #f9f9f9;">
          <div style="font-size: 14px; color: #666; margin-bottom: 8px;">${stat.label}</div>
          <div style="font-size: 24px; font-weight: bold; color: #395192;">${stat.value}</div>
        </div>
      `;
    });
    html += '</div>';
  }

  // Add sections
  data.sections.forEach(section => {
    html += `
      <h2>${section.heading}</h2>
      ${section.content}
    `;
  });

  return html;
}

/**
 * Export JSON data (for debugging or backup)
 */
export function downloadJSON(data: any, filename: string): void {
  const json = JSON.stringify(data, null, 2);
  const blob = new Blob([json], { type: 'application/json' });
  const link = document.createElement('a');
  
  const url = URL.createObjectURL(blob);
  link.setAttribute('href', url);
  link.setAttribute('download', `${filename}.json`);
  link.style.visibility = 'hidden';
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}

/**
 * Copy data to clipboard
 */
export async function copyToClipboard(text: string): Promise<boolean> {
  try {
    await navigator.clipboard.writeText(text);
    return true;
  } catch (error) {
    console.error('Failed to copy to clipboard:', error);
    // Fallback for older browsers
    const textArea = document.createElement('textarea');
    textArea.value = text;
    textArea.style.position = 'fixed';
    textArea.style.left = '-999999px';
    document.body.appendChild(textArea);
    textArea.select();
    try {
      document.execCommand('copy');
      document.body.removeChild(textArea);
      return true;
    } catch (err) {
      document.body.removeChild(textArea);
      return false;
    }
  }
}
